프로젝트 설정
CollaBu/pennyway-client-webview pull request #3
Opened 2024-04-04 12:22 UTC by Legitgoons

## 작업 이유
- 프로젝트 초기 설정
<br/>

## 작업 사항
#### 프로젝트 설정
- yarn berry와 vite를 사용해서 Project를 생성했습니다.
- 사용 합의된 라이브러리들도 모두 설치했습니다.
- React Router의 경우 createRouter로 설정했습니다.
- msw와 react-query-devtools 등 개발용 패키지들은 devDependencies에 설치하였습니다.
- path alias를 설정하였습니다.

#### 폴더구조 설정
- 합의사항에 따라 FSD와 모듈 아키텍처를 적절히 혼합하여 폴더구조를 설정하였습니다.
<br/>

#### Readme 작성
- 프로젝트 기본 설명을 작성하였습니다.

## 리뷰어가 중점적으로 확인해야 하는 부분
- [ ] 설정이 정상적으로 완료되었는지
- [ ] 폴더구조가 합의사항에 알맞게 구현되었는지 
- [ ] Readme가 정상적으로 작성되었는지
<br/>

## 발견한 이슈
#### cannot find module
- yarn berry에서 cannot find module이 발생하는 이슈가 있었습니다.
- 공식 홈페이지에 따라 corepack enable로 설정
- 그리고 https://xionwcfm.tistory.com/283 이 글을 참조하여 이슈를 해결하였습니다.

2024-04-04 14:01 UTC, BangDori requested changes
코드 리뷰는 디스코드 공지방에 공유되어있는 [코드 리뷰 in 뱅크샐러드 개발 문화](https://blog.banksalad.com/tech/banksalad-code-review-culture/) 참고해서 작성해봤습니다!

설정이랑 README 부분에서는 크게 문제되는 부분은 없어보이지만, FSD Architecture의 구조에 알맞게 React-Query랑 React-Router 초기 설정 부분을 app 폴더 내부로 옮겨주는게 좋을 것 같아보입니다!

고생하셨습니당!

2024-04-04 14:01 UTC, BangDori commented on .gitignore
P1: 환경변수가 포함될 `.env`를 **.gitignore에 추가**해주시면 좋을 것 같습니다.

2024-04-04 14:01 UTC, BangDori commented on vite.config.ts.timestamp-1710052688528-e446223f48bc3.mjs
P2: vite.config.ts.tiemstamp 파일은 해당 타임스탬프에 대한 설정 파일인 것 같은데, 프로젝트에 굳이 필요하지 않은 파일인 것 같습니다.

2024-04-04 14:01 UTC, BangDori commented on src/main.tsx
P2: QueryClientProvider와 RouterProvider 설정 같은 경우에는 Application 실행에 있어 필요한 설정으로 FSD Architecture의 구조 상 app 폴더에 각각 위치하는 것이 좋을 것 같습니다!

```
📦src
 ┣ 📂app
 ┃ ┣ 📂provider
 ┃ ┃ ┣ 📜query-client.ts
 ┃ ┣ 📂router
 ┃ ┃ ┗ 📜index.ts
 ┃ ┗ 📜App.tsx
```

2024-04-04 14:01 UTC, BangDori commented on .eslintrc.cjs
P3: React Query ESLint Plugin을 추가해주면 좋을 것 같습니다.

- https://tanstack.com/query/v4/docs/eslint/eslint-plugin-query

2024-04-04 14:01 UTC, BangDori commented on src/App.css
P2: 아래는 프로젝트에 초기 설정에서 생성된 스타일 시트 파일인 것 같습니다. 지워도 될 것 같아요.

2024-04-04 14:01 UTC, BangDori commented on src/App.tsx
P2: App.tsx는 Application의 진입점 역할을 하는 컴포넌트로, app 폴더에 위치하는게 좋을 것 같습니다.

2024-04-04 14:01 UTC, BangDori commented on src/index.css
P3: index.css도 위 App.css처럼 프로젝트 초기 설정에서 생성된 스타일 시트 파일이니, 지워도 될 것 같아요.

2024-04-04 14:01 UTC, BangDori commented on src/assets/react.svg
P2: 프로젝트에 초기 설정에서 생성된 svg 아이콘인 것 같습니다. 지워도 될 것 같아요.

2024-04-05 10:44 UTC, Legitgoons commented
> 코드 리뷰는 디스코드 공지방에 공유되어있는 [코드 리뷰 in 뱅크샐러드 개발 문화](https://blog.banksalad.com/tech/banksalad-code-review-culture/) 참고해서 작성해봤습니다!
> 
> 설정이랑 README 부분에서는 크게 문제되는 부분은 없어보이지만, FSD Architecture의 구조에 알맞게 React-Query랑 React-Router 초기 설정 부분을 app 폴더 내부로 옮겨주는게 좋을 것 같아보입니다!
> 
> 고생하셨습니당!

리뷰에서 지적해주신 부분들 모두 수정 완료했습니다! 확인 후 checklist 모두 눌러주시면 merge하겠습니당!

2024-04-05 10:47 UTC, BangDori requested changes
마지막으로 한 번만 더 확인 부탁드릴게요!

2024-04-05 10:47 UTC, BangDori commented on src/main.tsx
> +  </React.StrictMode>,
P2: `QueryClientProvider`랑 `RouterProvider`를 애플리케이션의 진입점 역할을 하는 App.tsx에서 관리하는 것이 모듈 내 응집도가 높아져서 더 좋다고 생각합니다! 혹시 어떻게 생각하시나요?

2024-04-05 10:55 UTC, Legitgoons commented on src/main.tsx
> +  </React.StrictMode>,
이걸 빠트렸었네요 방금 수정했습니다!

2024-04-05 10:56 UTC, BangDori approved these changes
확인했습니다!! 문제없는 것 같아요.

고생하셨습니다~

2024-04-05 11:01 UTC, merged