⚙️ User Mock API 등록
CollaBu/pennyway-client-webview pull request #30
Opened 2024-05-05 16:33 UTC by Legitgoons

## 작업 이유
User API에 대한 Mock API 등록

<br/>

## 작업 사항
- [Wiki API Specification](https://github.com/CollaBu/pennyway-client-webview/wiki/API-Specification) 문서에 업로드 되어있는 API를 기반으로 하였습니다.
- User Interface에 feedCount, followingCount, followerCount를 추가했습니다.
- ProfileFeed Interface와 Relationship Interface를 구현했습니다.

<br/>

## 리뷰어가 중점적으로 확인해야 하는 부분
- [ ] ProfileFeed Interface와 Relationship Interface가 추가된 것을 인지했는지
- [ ] User Interface에 feedCount, followingCount, followerCount가 추가된 것을 인지했는지
- [ ] 구현된 항목들이 API Wiki와 일치하는지
- [ ] userHandler가 정상적으로 구현되었는지

<br/>

## 발견한 이슈

2024-05-05 17:39 UTC, BangDori requested changes
컨벤션이 맞지 않는 부분이 있어서 이 부분만 수정해주시면 될 것 같습니다! ㅎㅎ

고생많으셨습니다.

2024-05-05 17:39 UTC, BangDori commented on src/app/mocks/handler/user.ts
> +      hasNext,
P1: 저희 `hasNext` 말구 `hasNextPage` 로 통일하기루 했습니다!! [피드 목록 조회 API](https://github.com/CollaBu/pennyway-client-webview/wiki/Feed-API-Specification#1%EF%B8%8F%E2%83%A3-%ED%94%BC%EB%93%9C-%EB%AA%A9%EB%A1%9D-%EC%A1%B0%ED%9A%8C) 확인해보시면 hasNextPage로 되어 있습니당!

2024-05-05 17:39 UTC, BangDori commented on src/shared/consts/types/user.d.ts
> +export interface Relationship {
P2: 저희 Wiki에 등록한 [Type & Interface Rule](https://github.com/CollaBu/pennyway-client-webview/wiki/Type-%26-Interface-Rule) 확인해보시면, 단일 변수의 경우에는 `type`을 사용하기로 했어요!!

`RelationShipStatus`은 `interface`보다 `type`으로 변경하는 게 좋을 것 같아요!

2024-05-06 06:24 UTC, Legitgoons commented on src/app/mocks/handler/user.ts
> +      hasNext,
넵 수정 완료했습니다!

2024-05-06 06:24 UTC, Legitgoons commented on src/shared/consts/types/user.d.ts
> +export interface Relationship {
넵 type으로 수정했습니다!

2024-05-06 06:26 UTC, BangDori approved these changes
확인했습니다!!~

2024-05-06 06:32 UTC, merged