✨ Profile User Api
CollaBu/pennyway-client-webview pull request #79
Opened 2024-05-24 06:07 UTC by Legitgoons

## 작업 이유

<br/>

## 작업 사항

<br/>

## 리뷰어가 중점적으로 확인해야 하는 부분

<br/>

## 발견한 이슈
#75 이슈가 그대로 발생하고 있습니다.

2024-05-27 01:47 UTC, BangDori requested changes
프로필 하단에 사용자의 게시물은 다음 PR에서 진행하시는 건가용?

2024-05-27 01:47 UTC, BangDori commented on src/pages/profile/ui/ProfileMainPage.tsx
> +  if (formattedUserId === 1) {
P2: if 문에 있는 분기 처리를 isOwner props로 처리해주는 게 더 가독성이 좋지 않을까요?

2024-05-27 01:47 UTC, BangDori commented on src/shared/ui/profile/Profile.tsx
> +  linkedUserId?: number;
P3: PR에 optional prop으로 설정하신 이유가 명확하게 나오지 않은 것 같아요! 제 생각으로는 optional prop이 아닌 그냥 prop으로 넘겨줘도 문제되는 상황은 없다고 생각하는데, 혹시 optional로 설정한 이유가 무엇인가요~

2024-05-27 01:47 UTC, BangDori commented on src/widgets/profile-user/api/useGetUser.ts
> +    enabled: !!userId,
P4: 해당 키워드는 enabled가 0일 경우에만 false로 설정되고, 1 이상일 경우에는 enabled가 true로 설정되는 것 같습니다. 근데 userPK값은 1부터 시작하니까 무조건 true로 설정될 것 같은데, 이렇게 설정하신 이유가 있나요?

2024-05-27 01:47 UTC, BangDori commented on src/widgets/profile-user/assets/profile-change-icon.svg
P5: 이 부분 인지하고 계시다가, #75 이슈 해결하면 Sprite에 추가해서 병합 부탁드릴게용!

2024-05-27 01:47 UTC, BangDori commented on src/widgets/profile-user/ui/ProfileUser.tsx
> +  if (isError || !data) {
P3: 조건문에 data가 없는 경우를 함께 처리하는 이유가 있을까요?

2024-05-27 01:47 UTC, BangDori commented on src/widgets/profile-user/ui/ProfileUser.tsx
> +  }
P3: 에러가 발생했을 경우 에러 메시지 혹은 에러 UI가 피그마에 나오지 않아 있는 것 같은데 임시로 추가해두신 건가용?

2024-05-27 01:47 UTC, BangDori commented on src/widgets/profile-user/ui/ProfileUser.tsx
>    return (
P3: JSX 내부에 연산자와 함께 작성되어 있는 부분이 총 3가지 인데, 이거 profile-user/ui에 컴포넌트로 분리해도 좋을 것 같아요.

- L34-L49: 프로필 이미지와 관련된 컴포넌트
- L52-L56: 사용자가 주인인지 여부에 따라 다른 버튼을 렌더링하는 컴포넌트

2024-05-29 06:33 UTC, Legitgoons commented on src/shared/ui/profile/Profile.tsx
> +  linkedUserId?: number;
ProfilePage 내부에서도 Profile 컴포넌트가 출력되는데, 이 때 ProfiePage 내부 feed의 Profile Icon을 클릭한다면 리랜더링이 일어날 가능성이 있다고 생각해 optional로 설정하였습니다.

이와 함께 Feed 컴포넌트도 수정해야하는데, 이 작업은 추후 ProfileFeed 기능을 구현하며 함께 진행하도록 하겠습니다!

2024-05-29 06:38 UTC, Legitgoons commented on src/pages/profile/ui/ProfileMainPage.tsx
> +  if (formattedUserId === 1) {
그렇네요. if문을 먼저 구현하고 추후에 isOwner prop을 추가하면서 놓친 것 같습니당

2024-05-29 06:40 UTC, Legitgoons commented on src/widgets/profile-user/ui/ProfileUser.tsx
> +  if (isError || !data) {
저희 서버의 response값은 반드시 null을 사용하지 않도록 정의되어 있기에, data가 없는 경우라면 에러일 가능성이 매우 높다고 생각하여 함께 처리했습니다.

2024-05-29 06:40 UTC, Legitgoons commented on src/widgets/profile-user/ui/ProfileUser.tsx
> +  }
이 부분을 디자인팀 질문드렸는데, 해당 UI를 공통으로 사용하면 된다고 알려주셔서 추가하였습니다!

2024-05-29 07:09 UTC, Legitgoons commented on src/widgets/profile-user/ui/ProfileUser.tsx
>    return (
L34-49의 경우에는 따로 컴포넌트로 분리하는게 더 가독성에 도움이 될 것 같습니다.
L52-56은 아직은 크게 분리할 이유를 모르겠는데, 혹시 왜 이렇게 생각했는지 알려주실 수 있나요?

2024-05-29 07:11 UTC, Legitgoons commented on src/widgets/profile-user/api/useGetUser.ts
> +    enabled: !!userId,
이 부분은 혹시라도 userPK값이 없거나, 0인 상태에서 호출이 일어나지 않도록 하기 위해서 설정했습니다.

2024-05-29 07:17 UTC, BangDori commented on src/widgets/profile-user/api/useGetUser.ts
> +    enabled: !!userId,
userPK 값은 웹뷰를 로드할 때, iOS에서 받아오는 값이기 때문에 굳이 고려하지 않아도 되지 않을까요?

2024-05-29 07:23 UTC, BangDori commented on src/widgets/profile-user/ui/ProfileUser.tsx
> +  if (isError || !data) {
data가 없는 경우라면, !data 값이 true로 반환되어야 할 것으로 예상됩니다. 하지만 data에 `{}` 빈 객체가 저장되어 반환 값으로 true가 나오게 됩니다.

2024-05-29 07:23 UTC, BangDori commented on src/widgets/profile-user/ui/ProfileUser.tsx
> +  }
확인했습니다!!

2024-05-29 07:25 UTC, BangDori commented on src/widgets/profile-user/ui/ProfileUser.tsx
>    return (
제가 생각하기에 L52-56 자신의(닉네임 수정) 혹은 다른 사용자들의(팔로우) 액션을 나타내는 버튼으로 ProfileActionBtn으로 가독성이 향상될 수 있다고 생각하였습니다!

2024-05-29 07:31 UTC, Legitgoons commented on src/widgets/profile-user/api/useGetUser.ts
> +    enabled: !!userId,
아 그렇네요. iOS에서 가져오기 때문에 애초에 없을수가 없네요; 불필요하기 때문에 제거하겠습니다!

2024-05-29 08:02 UTC, Legitgoons commented on src/shared/ui/profile/Profile.tsx
> +  linkedUserId?: number;
이 부분은 좀 더 고민해봤는데, ProfileImage를 따로 컴포넌트로 분리하는게 좀 더 나을 것 같습니다. 현재의 방안은 Profile 컴포넌트에서 3항 연산자 내부에 또 3항 연산자가 들어가는 방식이라 지나치게 가독성이 떨어집니다.

또한 Profile 컴포넌트에 userId와 isLinked를 props로 전달하도록 해 이에 따라 link 여부를 결정하도록 수정하겠습니다.

2024-05-29 11:02 UTC, BangDori commented on src/shared/ui/profile/Profile.tsx
> +  linkedUserId?: number;
넵 확인했습니다.

2024-05-29 11:06 UTC, BangDori approved these changes
확인했습니당~

2024-05-29 11:14 UTC, merged